# Generated by Django 4.1.3 on 2022-11-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0005_rename_created_on_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=300),
        ),
    ]
